### ISSUE TITLE
`run.py` doesn't run

### ISSUE THREAD

**Issue by davidschlangen** [clp-research/golmi#50]
In a new conda environment (python 3.10), on macos, after installing the requirements (w/o problems), I cannot successfully run `run.py` as per the instructions.

Expected output: A running server.

Seen output:
```
(golmi) golmi % python run.py 
Traceback (most recent call last):
  File "/Users/das/mst22_synced/work/svn/Gits/a_Projects/Projects/Infrastructure/golmi/run.py", line 5, in <module>
    from app.app import app, socketio
  File "/Users/das/mst22_synced/work/svn/Gits/a_Projects/Projects/Infrastructure/golmi/app/app.py", line 6, in <module>
    from flask_socketio import (
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/Users/das/anaconda3/envs/golmi/lib/python3.10/site-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
Exit 1
```

Some problem with the versions required by `requirements.txt`?

**Comment by davidschlangen** [comment]
Does indeed seem to be a python 3.10 issue, with python 3.9 it runs. Kind of.
